// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_L0gOGRva5EpvPdQBnKVgOTxknqktK10',
    appId: '1:1002585463000:web:5f85fdc5d4d907e13adfad',
    messagingSenderId: '1002585463000',
    projectId: 'coffeapp-5f3f0',
    authDomain: 'coffeapp-5f3f0.firebaseapp.com',
    storageBucket: 'coffeapp-5f3f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYsv5JPpPoKMGQcoCdGvG1eTVXWrPlzgA',
    appId: '1:1002585463000:android:5c0c0aba67d3b6943adfad',
    messagingSenderId: '1002585463000',
    projectId: 'coffeapp-5f3f0',
    storageBucket: 'coffeapp-5f3f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZA9wVtnZt6sX0aEQVOwI1Hr5Ods-oAqA',
    appId: '1:1002585463000:ios:93f853ea75c9d4993adfad',
    messagingSenderId: '1002585463000',
    projectId: 'coffeapp-5f3f0',
    storageBucket: 'coffeapp-5f3f0.appspot.com',
    iosClientId:
        '1002585463000-s0siohce5qp9a59j1v4un4ijftti2j6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZA9wVtnZt6sX0aEQVOwI1Hr5Ods-oAqA',
    appId: '1:1002585463000:ios:da971ffe51c8f9303adfad',
    messagingSenderId: '1002585463000',
    projectId: 'coffeapp-5f3f0',
    storageBucket: 'coffeapp-5f3f0.appspot.com',
    iosClientId:
        '1002585463000-5l8gr9b35vfqenfbm4nbpiqd476pomhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeapp.RunnerTests',
  );
}
